include tempered-colors.conf
font_family JetBrainsMono Nerd Font
font_size 10.5
window_padding_width 10
background_opacity 0.82
background_blur 22
dynamic_background_opacity yes
confirm_os_window_close 0
cursor_shape beam
cursor_blink_interval 0
tab_bar_style powerline
tab_powerline_style slanted
inactive_text_alpha 0.72
