foreground #eef5ff
background #121923
selection_foreground #121923
selection_background #7ebeff
cursor #7ebeff
color0 #121923
color1 #ff7482
color2 #9a92ff
color3 #b6d4ef
color4 #7ebeff
color5 #9a92ff
color6 #b6d4ef
color7 #eef5ff
